from models import OpcodeInfo

OPCODES = {
    "ADD": OpcodeInfo("ADD", 3, 0x18),
    "ADDF": OpcodeInfo("ADDF", 3, 0x58),
    "ADDR": OpcodeInfo("ADDR", 2, 0x90),
    "AND": OpcodeInfo("AND", 3, 0x40),
    "CLEAR": OpcodeInfo("CLEAR", 2, 0xB4),
    "COMP": OpcodeInfo("COMP", 3, 0x28),
    "COMPF": OpcodeInfo("COMPF", 3, 0x88),
    "COMPR": OpcodeInfo("COMPR", 2, 0xA0),
    "DIV": OpcodeInfo("DIV", 3, 0x24),
    "DIVF": OpcodeInfo("DIVF", 3, 0x64),
    "DIVR": OpcodeInfo("DIVR", 2, 0x9C),
    "FIX": OpcodeInfo("FIX", 1, 0xC4),
    "FLOAT": OpcodeInfo("FLOAT", 1, 0xC0),
    "HIO": OpcodeInfo("HIO", 1, 0xF4),
    "J": OpcodeInfo("J", 3, 0x3C),
    "JEQ": OpcodeInfo("JEQ", 3, 0x30),
    "JGT": OpcodeInfo("JGT", 3, 0x34),
    "JLT": OpcodeInfo("JLT", 3, 0x38),
    "JSUB": OpcodeInfo("JSUB", 3, 0x48),
    "LDA": OpcodeInfo("LDA", 3, 0x00),
    "LDB": OpcodeInfo("LDB", 3, 0x68),
    "LDCH": OpcodeInfo("LDCH", 3, 0x50),
    "LDF": OpcodeInfo("LDF", 3, 0x70),
    "LDL": OpcodeInfo("LDL", 3, 0x08),
    "LDS": OpcodeInfo("LDS", 3, 0x6C),
    "LDT": OpcodeInfo("LDT", 3, 0x74),
    "LDX": OpcodeInfo("LDX", 3, 0x04),
    "LPS": OpcodeInfo("LPS", 3, 0xD0),
    "MUL": OpcodeInfo("MUL", 3, 0x20),
    "MULF": OpcodeInfo("MULF", 3, 0x60),
    "MULR": OpcodeInfo("MULR", 2, 0x98),
    "NORM": OpcodeInfo("NORM", 1, 0xC8),
    "OR": OpcodeInfo("OR", 3, 0x44),
    "RD": OpcodeInfo("RD", 3, 0xD8),
    "RMO": OpcodeInfo("RMO", 2, 0xAC),
    "RSUB": OpcodeInfo("RSUB", 3, 0x4C),
    "SHIFTL": OpcodeInfo("SHIFTL", 2, 0xA4),
    "SHIFTR": OpcodeInfo("SHIFTR", 2, 0xA8),
    "SIO": OpcodeInfo("SIO", 1, 0xF0),
    "SSK": OpcodeInfo("SSK", 3, 0xEC),
    "STA": OpcodeInfo("STA", 3, 0x0C),
    "STB": OpcodeInfo("STB", 3, 0x78),
    "STCH": OpcodeInfo("STCH", 3, 0x54),
    "STF": OpcodeInfo("STF", 3, 0x80),
    "STI": OpcodeInfo("STI", 3, 0xD4),
    "STL": OpcodeInfo("STL", 3, 0x14),
    "STS": OpcodeInfo("STS", 3, 0x7C),
    "STSW": OpcodeInfo("STSW", 3, 0xE8),
    "STT": OpcodeInfo("STT", 3, 0x84),
    "STX": OpcodeInfo("STX", 3, 0x10),
    "SUB": OpcodeInfo("SUB", 3, 0x1C),
    "SUBF": OpcodeInfo("SUBF", 3, 0x5C),
    "SUBR": OpcodeInfo("SUBR", 2, 0x94),
    "SVC": OpcodeInfo("SVC", 2, 0xB0),
    "TD": OpcodeInfo("TD", 3, 0xE0),
    "TIO": OpcodeInfo("TIO", 1, 0xF8),
    "TIX": OpcodeInfo("TIX", 3, 0x2C),
    "TIXR": OpcodeInfo("TIXR", 2, 0xB8),
    "WD": OpcodeInfo("WD", 3, 0xDC),
}

DIRECTIVES = {
    "START", "END", "BYTE", "WORD", "RESB", "RESW", "EQU", "USE", "BASE"
}